### PR TITLE
Auto-startup for windows

### PR DESCRIPTION
**Pull request by GrayHatter**
replaces #931

### CODE REVIEW

**Comment by irungentoo** [comment]
```
../av/uTox/win32/main.c:2493:13: warning: implicit declaration of function ‘RegSetKeyValueA’ [-Wimplicit-function-declaration]
             ret = RegSetKeyValueA(hKey, NULL, "uTox", REG_SZ, path, path_length);
             ^
../av/uTox/win32/main.c:2504:13: warning: implicit declaration of function ‘RegDeleteKeyValueA’ [-Wimplicit-function-declaration]
             ret = RegDeleteKeyValueA(hKey,NULL,"uTox");
```

**Comment by GrayHatter** [comment]
@irungentoo fixed and rebased off master

**Comment by GrayHatter** [comment]
@irungentoo as requested, start-on-boot flags for use with the updater

**Comment by GrayHatter** [comment]
just rebased off master, this likely breaks the clean merge, if so let me know and I'll fix it

**Comment by GrayHatter** [comment]
rebased again, should just work (TM)

**Comment by GrayHatter** [comment]
included in #1029 this version breaks xp

**Pull request closed without merging**
