### PR TITLE
Adds ablity to set an alias for each friend

### LINKED ISSUE #190: Give contacts an alias
There was a discussion on the ability to change names at will, with the only constant being the ID code for a user here irungentoo/toxcore#756.

I was wondering if it would be possible to implement an alias function into uTox with it's own save, since toxcore is leaving it up to the clients. I was looking at possibilities for implementing this, but I thought I'd open discussion on it as well.

### PR DESCRIPTION
**Pull request by GrayHatter**
todo persist across restarts

closes #190

### CODE REVIEW

**Comment by GrayHatter** [comment]
I'm open to suggestions on how to save the alias across reboots...

should each friend have their own file like they do for history? Or should everything be grouped into utox_save? Or something else entirely?

**Comment by tsudoko** [comment]
A separate file for all aliases, for example utox_aliases?

**Comment by nachfuellbar** [comment]
I think there should be one solution for aliases which every client supports (create one standard file and describe this in Tox STS)

**Comment by irungentoo** [comment]
Some strange issues when setting the alias with the alias command.

T
utox_the_future1
hat triangle is a NULL character.

**Comment by GrayHatter** [comment]
@irungentoo fixed

todo: [ ] save aliases to a file...

**Comment by GrayHatter** [comment]
@irungentoo would you rather a separate save file for each friend? Or a single save file with every friend wrapped together?

**Comment by GrayHatter** [comment]
just rebased off master

**Comment by GrayHatter** [comment]
@irungentoo can I merge this?

**Comment by GrayHatter** [comment]
@irungentoo

**Pull request merged**
