### PR TITLE
Rewrote Spanish translations

### PR DESCRIPTION
**Pull request by GranPC**
Also, here are some questions/suggestions!
- Where are "CALL_INVITED" and "CALL_RINGING" used? I'm not sure how to translate those and it would probably help if I had more context information.
- "Loopback" is a bit of a technical word without an appropriate translation. I'd imagine native English speakers without tech knowledge might be confused by it too.
- "THEME_CUSTOM" is pretty bad, since it doesn't even offer a link to the documentation. It would be pretty cool if uTox could just hide it until a custom theme has been installed, and add a label/link to the specific part of the documentation that explains how to create custom themes.

### CODE REVIEW

**Comment by GrayHatter** [comment]
@GranPC thank you for this pull request!

CALL_INVITED and CALL_RINGING are used in the message/chat window for a contact, it's a little notice line that's added so the user can track which call was when, and what what said in chat before and after. I've merged this into develop in my branch https://github.com/grayhatter/utox

**Comment by GranPC** [comment]
@GrayHatter cool! I will look into improving those two strings then.

Is your branch the new 'official' one for this client? I've noticed that @notsecure hasn't been around for a while.

**Comment by GrayHatter** [comment]
@GranPC I'm moving all of my development over to there, for that exact reason.

**Comment by GranPC** [comment]
I'll keep an eye there then. Thank you!

**Pull request merged**
