### PR TITLE
Ubuntu Unity's integration: first step

### PR DESCRIPTION
**Pull request by Encrypt**
This is the first step in Ubuntu Unity's integration as requested on #758 by @mrbiber and @shalnoff.

When µTox is minimized and when a notification is raised, the "mail" icon in the Messaging menu turns blue.
In the Messaging Menu, the nickname of the friend is displayed with the number of minutes when this event happened. A preview is available in the issue #758.

When Tox is maximized again, the "source" disappear from the messaging menu if the current friend is the one who sent a message.
It also removes the source when the user clicks on the friend(s) who sent the message(s).

I'd like to know what Ubuntu users think about it for the moment.
I'm also planning to add a message count in the dock and make µTox open when the user clicks on the associated source un the messaging menu.
Minimizing to tray is also a feature which will be implemented.

**Note for @irungentoo :** A new dependency is needed, which is the messaging-menu.
I modified the makefile accordingly, and it is possible to disable Unity's integration setting UNITY=0.

### CODE REVIEW

**Comment by Nsheppard01** [comment]
What about Xubuntu and other forks that use other DEs?

**Comment by tsudoko** [comment]
I don't think `UNITY` should be `1` by default, most distributions don't use Unity.

**Comment by Encrypt** [comment]
Right, I just chaned it to 0! ;)

@irungentoo will have to adapt it (set it as 1) in Jenkins for deb packages ; as well as for rpm packages maybe, since it seems possible to install Unity in Arch...

**Comment by GrayHatter** [comment]
does debian install unity by default? or is that a ubuntu thing?

**Comment by Nsheppard01** [comment]
Ubuntu only.

**Comment by Encrypt** [comment]
Unity is the default desktop environment on Ubuntu.
However, it is possible to install it in Debian and other GNU/Linux distros...

If you have had a look at my code, you should have noticed that if the current desktop environment used is not Unity, then all the messaging menu integration functions won't be executed! ;)
So, it is possible to include it in the deb package with no problem for those who don't run Unity!

@Nsheppard01: I had planned to work on Unity integration (that's a feature I wanted, so I decided to become a µTox developer :p). I may have a look at other desktop environment later.

**Comment by Encrypt** [comment]
New feature!

A number is now displayed above the µTox icon in the dock when friends send you messages.
This number corresponds to the number of friends who wrote without your having a look / replying.

Here is a preview:
tox_icon_dock

**Pull request merged**
