### PR TITLE
Cancel call

### PR DESCRIPTION
**Pull request by draziw-**
Users can now cancel ringing call.

### CODE REVIEW

**Comment by GrayHatter** [comment]
The indentation is mixed case in a few of the files. 

@draziw- you should change the tabs to spaces to keep form with the rest of the code.

**Comment by draziw-** [comment]
fixed, thank you for noticing

/* I have fixed emacs for utox, this should not happen anymore */

**Comment by Doom032** [comment]
Hey I tested it and it works well but wouldn't it be more intuitive if you could cancel your video call by clicking the video button instead of the audio call button?

**Comment by v2e** [comment]
Is this available in Xlib version?

**Comment by GrayHatter** [comment]
@v2e clone it and find out!

(yes)

**Pull request merged**
