### PR TITLE
new_api File transfers and Avatars now work

### PR DESCRIPTION
**Pull request by GrayHatter**
coming soon inline transfers

~~pull after #918~~

replaces #918

### CODE REVIEW

**Comment by irungentoo** [comment]
```
=================================================================
==8101==ERROR: AddressSanitizer: attempting double-free on 0x616000020180 in thread T1:
    #0 0x4b612b in __interceptor_free (/home/gent/programming/free-skype/av/uTox/uTox+0x4b612b)
    #1 0x3d7e46e93c in fclose (/lib64/libc.so.6+0x3d7e46e93c)
    #2 0x5396be in utox_complete_file /home/gent/programming/free-skype/av/uTox/file_transfers.c:466:9
    #3 0x539074 in outgoing_file_callback_chunk /home/gent/programming/free-skype/av/uTox/file_transfers.c:366:9
    #4 0xf37436 in do_reqchunk_filecb /home/gent/programming/free-skype/av/ProjectTox-Core/build/../toxcore/Messenger.c:1453:25
    #5 0xf37436 in do_friends /home/gent/programming/free-skype/av/ProjectTox-Core/build/../toxcore/Messenger.c:2227
    #6 0xf3ae86 in do_messenger /home/gent/programming/free-skype/av/ProjectTox-Core/build/../toxcore/Messenger.c:2305:5
    #7 0xf46a48 in tox_iterate /home/gent/programming/free-skype/av/ProjectTox-Core/build/../toxcore/tox.c:353:5
    #8 0x65b2af in tox_thread /home/gent/programming/free-skype/av/uTox/tox.c:626:13
    #9 0x3d7f0091d9 in start_thread (/lib64/libpthread.so.0+0x3d7f0091d9)
    #10 0x3d7e4edbec in clone (/lib64/libc.so.6+0x3d7e4edbec)

```

**Comment by irungentoo** [comment]
```
#0  0x00000000004c9550 in __sanitizer::internal_strlen(char const*) ()
#1  0x000000000045fe7e in printf_common(void*, char const*, __va_list_tag*) ()
#2  0x00000000004615ea in printf ()
#3  0x000000000067d7a4 in tox_message (tox_message_id=<optimized out>, param1=<optimized out>, param2=<optimized out>, 
    data=<optimized out>) at tox.c:1547
#4  0x00000000005a8a03 in doevent (event=...) at ./xlib/event.c:491
#5  0x00000000005b3c2a in main (argc=<optimized out>, argv=<optimized out>) at ./xlib/main.c:1130
```

**Comment by irungentoo** [comment]
```
Legacy call:    You shouldn't see this, please file a bug report!
Legacy call:             msg(29) param1(29) param2(0)Legacy call:       You shouldn't see this, please file a bug report!
Legacy call:             msg(29) param1(29) param2(1)Legacy call:       You shouldn't see this, please file a bug report!
Legacy call:             msg(29) param1(29) param2(2)Legacy call:       You shouldn't see this, please file a bug report!
Legacy call:             msg(29) param1(29) param2(3)
```

**Comment by irungentoo** [comment]
```
messages.c:490:28: runtime error: index 15 out of bounds for type 'const uint8_t [14]'
=================================================================
==10318==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000010464af at pc 0x0000005df9d8 bp 0x7fffffff7e70 sp 0x7fffffff7e68
READ of size 1 at 0x0000010464af thread T0
    #0 0x5df9d7 in messages_mmove /home/gent/programming/free-skype/av/uTox/messages.c:490:20
    #1 0x6d3b35 in panel_mmove /home/gent/programming/free-skype/av/uTox/ui.c:1132:28
    #2 0x6d457b in panel_mmove /home/gent/programming/free-skype/av/uTox/ui.c:1141:25
    #3 0x6d457b in panel_mmove /home/gent/programming/free-skype/av/uTox/ui.c:1141:25
    #4 0x6d457b in panel_mmove /home/gent/programming/free-skype/av/uTox/ui.c:1141:25
    #5 0x59e5d9 in doevent /home/gent/programming/free-skype/av/uTox/./xlib/event.c:125:9
    #6 0x5b3c68 in main /home/gent/programming/free-skype/av/uTox/./xlib/main.c:1124:13
    #7 0x3d7e424db4 in __libc_start_main (/lib64/libc.so.6+0x3d7e424db4)
    #8 0x4d3a2c in _start (/home/gent/programming/free-skype/av/uTox/uTox+0x4d3a2c)

```

**Comment by tsudoko** [comment]
https://gist.github.com/tsudoko/03cae97ce8539a5e1239

**Comment by irungentoo** [comment]
https://github.com/notsecure/uTox/tree/new_api_ft

Fixed a couple things.

**Pull request merged**
