### PR TITLE
File system enhansements for win32 + *nix

### LINKED ISSUE #166: µTox doesn't check whether has permissions to save file
When saving file from file transfer, µTox lets user to “save” file in directories where user doesn't have permission to do so.

User should be prompted that permissions are insufficient to save file, and prompted to save file in other place.

### PR DESCRIPTION
**Pull request by GrayHatter**
might close #166 (maybe)

windows, *nux:
    prompt before overwriting
windows:
    enforce write ablity via os

### CODE REVIEW

**Comment by tsudoko** [comment]
Could you also make it save the file with permissions `-rw-------` on *nixes? Currently it's readable by all the users.

**Comment by GrayHatter** [comment]
@tsudoko good catch, I will.

**Comment by irungentoo** [comment]
What happened to the commits here?

**Comment by GrayHatter** [comment]
I dun goofed trying to prune some branches after midnight...

I'll rebase that changes that SHOULD have been in this commit, and submit a new pull. I'll close this one once I'm done so that I can reference this history...

Sorry guys.

**Pull request closed without merging**
