### PR TITLE
Lower send button to close 272

### LINKED ISSUE #272: send button
The free space under the screenshot button looks strange and ugly. Please, add there a button to send message or smiles.

### PR DESCRIPTION
**Pull request by GrayHatter**
closes #272

### CODE REVIEW

**Comment by tsudoko** [comment]
Why is the icon a "+"?

**Comment by GrayHatter** [comment]
because I haven't looked into the drawalpha code yet, so I'm still not sure how to write my own graphic.

Plus and I haven't decided on what graphic should actually be there. Any suggestions?

**Comment by Doom032** [comment]
drawing new graphics can be done in the svg_draw function in svg.c. You'll also have to add an entry to the "sysmenu icons" enum in main.h, define the sizes in svg.h, and increase the amount of data calloc'd in svg_draw.

Maybe an arrow to the right or something would be understandable. Or something like the enter key (↵ ?). I'd be in favor of changing the icon of the screenshot button to something like a stylized photo camera(rectangle with a circle in it or something) to prevent common confusion about it.

**Comment by GrayHatter** [comment]
Yeah, I understand the framework. I just don't know how to draw out the images we want, only because I don't even know what to put there.

**Comment by tsudoko** [comment]
uTox is supposed to follow [these guidelines](https://github.com/ItsDuke/Tox-UI), maybe they will help you.

**Pull request merged**
