### PR TITLE
UI refactor, rebuild the user settings page

### PR DESCRIPTION
**Pull request by GrayHatter**
todo 
 - [x] audio settings
 - [x] normalize the page height
 - [x] make the tabs look more like tabs (look into how utox draws the backgrounds)
 - [x] #542 
 - [x] revision tick

### CODE REVIEW

**Comment by GrayHatter** [comment]
closes #904

**Comment by GrayHatter** [comment]
todo fix #542 as well

**Comment by stal888** [comment]
Doesn't break anything here. :+1:

**Comment by GrayHatter** [comment]
@irungentoo

**Comment by towlie** [comment]
@GrayHatter 
unbenannt
Also I recommend to fix these overflow issue in a better way in general (maybe using per language spaces? or automatically detect needed space?) 
Because this is a big issue that uTox has accross languages when new things are added.

**Comment by GrayHatter** [comment]
The problem with using per language sizing is that first, there's no great way to decide how long a string is going to be. And when trying to size these tabs, getting overflow will become a huge problem. Even with the english text, if you narrow the window enough you lose tabs...

I don't know what a good solution for this is while still making it look good

**Comment by tsudoko** [comment]
@GrayHatter couldn't `drawtextwidth`/`drawtextrange` be used for text on tabs as a workaround?

**Comment by irungentoo** [comment]
Can you make your menu buttons change colour on mouse hover and make it switch when you click on the button (right now it only switches if you click on the text).

Clicking your name and status doesn't switch you to where you can change it.

In the Audio/Video the filter audio setting can be moved closer to the Ringtone setting.

Scrolling up and down in a setting makes the line on top disappear.

**Comment by GrayHatter** [comment]
- [x] name and status switch now
- [ ] av filter audio moved
- [ ] fix line scroll bug
- [ ] embegen button area, highlight on mouse over

**Comment by GrayHatter** [comment]
this next commit is optional, it shrinks the wasted space in the header for settings...

**Comment by towlie** [comment]
@GrayHatter "language" is in the profile tab it belongs to "user interface".
Also the close to tray button should be moved a lot more to the right because some translations are really long. I think you should check all translations to prevent further issues.
over

**Comment by tsudoko** [comment]
Does the "uTox Settings" label actually need to be there? Seems like it'd look fine without it.

**Comment by GrayHatter** [comment]
> @GrayHatter "language" is in the profile tab it belongs to "user interface".

I thought about that, but I left it in profile because I wanted it to be front and center so to speak in case you don't speak/read english.

**Comment by GrayHatter** [comment]
> Does the "uTox Settings" label actually need to be there? Seems like it'd look fine without it.

It's there for legacy reasons, but I don't know what to put there? Expanding the tabs to 30px seems like overkill.

**Comment by tsudoko** [comment]
Does it look bad with tabs at their current height, but without the settings label?

**Comment by tsudoko** [comment]
Also I'm not sure if the last tab should be so long, it looks a bit weird with a wide window and the last tab selected.

**Comment by GrayHatter** [comment]
> Also I'm not sure if the last tab should be so long, it looks a bit weird with a wide window and the last tab selected.

I could make them floating widths, but they'd look equally as bad center justified for huge window widths.

**Comment by stal888** [comment]
You don't have to make the tabs 30px tall, just move everything up

**Pull request merged**
