### PR TITLE
Start in tray

### PR DESCRIPTION
**Pull request by GrayHatter**
part of #719 

closes #812 

incorporates #811

### CODE REVIEW

**Comment by GrayHatter** [comment]
@tsudoko what language are you using?

**Comment by tsudoko** [comment]
Was Japanese when I started uTox, but after switching to English the strings were still wrong.

**Comment by GrayHatter** [comment]
@tsudoko have you tried  7087502

**Comment by tsudoko** [comment]
Turns out it was because I didn't `make clean` before recompiling, everything's fine now.

**Comment by irungentoo** [comment]
Start in tray option has no title.

**Comment by shalnoff** [comment]
please add tray icon in Linux distros

**Pull request merged**
