### PR TITLE
better positioning of localized strings depending on their width

### PR DESCRIPTION
**Pull request by slr**
ok

### CODE REVIEW

**Comment by GrayHatter** [comment]
image

can you rename x2 to something descriptive?

**Comment by slr** [comment]
I definitely can. now it's `x_right_edge`, hope you like it.

I thought it's common practice in drawing of boxes to name them like that:

    box(int x1, int y1, int x2, int y2)

**Comment by GrayHatter** [comment]
common practice, but still wrong... This is perfect! Thanks

I'll merge this once I get a chance to test it.

**Comment by GrayHatter** [comment]
@slr I never got your strings to line up correctly, there was always a little error rate on the sizes... so I added a precompiler function to do that job here https://github.com/GrayHatter/uTox/tree/slr-fix-localization-settings

**Comment by slr** [comment]
[great!](http://www.whosawesome.com)

there was issue with bad sizes of tabs after changing of DPI. I've fixed that and other misc things.

**Comment by GrayHatter** [comment]
@slr I haven't forgotten about this. It'll get merged in, but right now I'm working on a refactor of the UI code in general. So once that get's done I can dive back into this.

**Comment by GrayHatter** [comment]
@slr thank you for your patience I merged in the current master into the above branch.  If you could pull that down into your branch and fix the last two mis alignments ( the git v tag, and and the UI start in tray string and dropdown) This can get merged

Again, thanks for writing most of this!

**Comment by slr** [comment]
hey! I'm sorry for no responce, no problem with that. have you tried my last commit? that two misalignments is already fixed.
and no, thank _you_.

**Comment by GrayHatter** [comment]
Assuming I get home at a reasonable time, I'll try to merge this tonight

**Comment by GrayHatter** [comment]
@slr I hate to do this to you, but I need you to rebase off master for this one...

**Comment by slr** [comment]
[anything you want.](http://youtube.com/watch?v=Ovq2fpsA9Is)

**Comment by GrayHatter** [comment]
merged into develop @tsudoko

**Comment by GrayHatter** [comment]
@slr this is already pulled into develop in my branch, so I'm going to close this one here. Thanks @slr this is super awesome!

**Comment by slr** [comment]
@GrayHatter just don't stop on bringing the awesome!

**Pull request closed without merging**
