### PR TITLE
Ctrl-W support

### PR DESCRIPTION
**Pull request by gjedeer**
Ctrl-W to delete last word, like Unix shell.

### CODE REVIEW

**Comment by tsudoko** [comment]
Could you add ^U as well?

**Comment by draziw-** [comment]
This support windows too, it's in the cross-platform code.

**Comment by gjedeer** [comment]
@draziw- no, it isn't in the cross platform code. I'll add Windows support when I have time (although I have no idea how to test it, there's no clear windows build instruction)

**Comment by GrayHatter** [comment]
docs/BUILD.md and tools/cross-compile.sh

**Pull request merged**
