### PR TITLE
Adding avatars to the notifications using DBus

### PR DESCRIPTION
**Pull request by Encrypt**
I discussed with irungentoo (and other contributrors) on IRC about this "new feature" dealing with integration in GNU/Linux systems using DBus.

Now, when one receives a message from a friend and if uTox is minimized, the notification sent shows the avatar of the other friend next to the "name" and "message".

Exemple on Ubuntu in the picture bellow:
notification_with_avatar

### CODE REVIEW

**Comment by ReAzem** [comment]
:+1:

**Comment by Doom032** [comment]
Hey, I tested this on Xubuntu and it works well, screenshot:
inline

Also works if you don't have an avatar set, and no problems with compiling for windows.

Some small stuff in the code that can be improved(I wrote this to you in uTox as well but I'll copypaste it here for good measure):
 - xlib/dbus.c:3 You shouldn't include util.h here, because it's already being included when dbus.c is included, also I don't think you're actually using anything in util.h
 - friend.c:83 all utox code uses brackets around the body of if statements even if it's not strictly needed, I think it's good to do so because you won't get unexpected problems if you accidentally add something to the body
 - avatar.h:20 actually get_avatar_location doesn't think it can fail(it'd probably just crash if the id you give it is too small, but if it's the right byte size but makes no sense it'll just give you an unusable avatar location and always returns the amount of bytes written, so the comment should be changed
 - also a very minor point: I think the string_cid declaration in xlib/dbus.c:15 can better be moved to just above the cid_to_string call(line 26), because that's the only place it's used. It makes it clear it's not used outside of that context

If you fix that stuff I think it's all good.

**Comment by Doom032** [comment]
Your last commit addressed all my issues. Seems everything's good. Thanks!

**Comment by GrayHatter** [comment]
@Doom032 I admittly only scanned the code briefly, but didn't see any one-off ? : added. 

Or are you talking about functions() missing their { indentations }?

**Comment by Doom032** [comment]
@GrayHatter I wasn't talking about ?:, I was talking about if statements with 1 statement in their body, as in

```
if (1)
 do();
// vs
if (1) {
  do();
}
```

**Comment by GrayHatter** [comment]
I'm 50/50 on
```
if($this){
    than(that)
}
```
or 
``` is_true() ? than(that) : else(this)```

**Comment by Doom032** [comment]
Hm I think the former is clearer, because I've never seen the latter used for anything except pure expressions(where only the return value is of interest).

**Comment by GrayHatter** [comment]
Lets enforce the former then.

**Pull request merged**
