### PR TITLE
Set video window style mask to resizable on OS X.

### PR DESCRIPTION
**Pull request by astra-midnight**
I believe the style mask lacking the resizable option was in error so I'm submitting a pull request to correct it.

### CODE REVIEW

**Comment by stal888** [comment]
A couple of things here:

- Are you sure you want to allow free-resizing? I think setting the contentAspectRatio would be more user-friendly.
- GitHub says `video.m`'s permissions were changed to 755. Please set them back to 644.

After fixing/ignoring my advice, please rebase upon [grayhatter/uTox](/grayhatter/uTox) develop branch and submit this PR there; that is where current uTox dev is happening. You can tell him I said :+1:.

**Comment by GrayHatter** [comment]
@hachidorii any update on this? See @stal888's comment?

**Comment by giggle-engineer** [comment]
Been busy with a couple of other things and the last time I tried to change the aspect ratio it didn't work just quite right. It seemed off.

**Comment by GrayHatter** [comment]
@stal888 close or try to merge?

**Comment by stal888** [comment]
@GrayHatter what does windows do?

**Pull request closed without merging**
