### PR TITLE
Auto startup feature.

### PR DESCRIPTION
**Pull request by mattr0**

### CODE REVIEW

**Comment by GrayHatter** [comment]
@mattr0 thanks for the commits, I'm almost ready to pull it, if you can fix a few issues. 

- [ ] It needs a prototype with a short comments about the functions job in main.h
- [ ] android/main.c & xlib/main.c need a copy of the function you added as well (they can be empty but they must exist
- [ ] the path of utox.exe in the registry needs to be surrounded by double quotes for some directories. 

If you don't want to make these fixes, I'll get around to them eventually.

Thanks again for the PR!

**Comment by GrayHatter** [comment]
Re: you IRC comment. No, only main.h needs the prototype, your should also remove the one from win32/main.h so compilers don't get cranky.

Can you also fix the indentation mismatch? (Or maybe github is buggy)

**Comment by mattr0** [comment]
@GrayHatter Thank you for the reviews! I hope its fine now.

**Comment by GrayHatter** [comment]
@mattr0 looks really good thankyou!!

**Comment by GrayHatter** [comment]
@mattr0 can you please rebase on master?

**Comment by mattr0** [comment]
@GrayHatter I did the rebase, and reorganized my commits into a single commit. Sorry for the delay. :)

**Comment by GrayHatter** [comment]
@mattr0 there was another PR that conflicts with this. I've updated it in #968, you can pull that and update this, or I can just merge that one? Do you care which I use?

**Comment by mattr0** [comment]
@GrayHatter You can simply merge #968. Thanks.

**Pull request closed without merging**
