### PR TITLE
Adding Archlinux dependency information

### PR DESCRIPTION
**Pull request by muchweb**
This list is mainly based on [`utox-git`'s `PKGBUILD`](https://aur.archlinux.org/packages/ut/utox-git/PKGBUILD) by Madotsuki.

### CODE REVIEW

**Comment by tsudoko** [comment]
`tox-git` from AUR isn't really required if one builds toxcore from source, also `dbus-c++` is optional, would be nice to put information about that.

**Comment by GrayHatter** [comment]
Speaking as an Arch user, we shouldn't be distro specific. There's just too many flavors to fight with. We should just offer general specifics and leave it to their respective communities to package it for themselves. Debian, Gentoo, and Arch already have packages for utox, so making it easy for package maintainers should be our focus.

**Comment by muchweb** [comment]
>We should just offer general specifics and leave it to their respective communities to package it for themselves.

@GrayHatter, for packaging, yes, I agree, but, in my opinion, it is still handy to have distro-specific instructions for users that are willing to modify the source code and compile manually.

**Comment by GrayHatter** [comment]
Maybe create a distro specific directory with build instructions for each, then we can keep things like arch's PKGBUILD for the different distros just incase someone wants to git clone; make; make install?

Then allow maintainers to base off that, and commit when needed?

**Comment by ReAzem** [comment]
@GrayHatter https://github.com/Tox/Packaging

**Pull request merged**
