### PR TITLE
File resume refactor

### PR DESCRIPTION
**Pull request by GrayHatter**

### CODE REVIEW

**Comment by GrayHatter** [comment]
@irungentoo per your comment on #972 I've cleaned up the code a bit. And only use the saved info from the files to restore existing files.

I'm starting on figuring out how to replace the file transfer bar, but I think I'm also going to wrap that into saving file transfers to the log file as well, that way any file including completed/* can be restored across restarts. It's something that I think is required as it fixes continuity... 

please forgive any incoherencies, my brain turned off an hour ago!

**Comment by irungentoo** [comment]
https://gist.github.com/irungentoo/164a7771e859bbc53a7f

Some threading fixes I made.

Can you get rid of TOX_FILE_KIND_EXISTING?

**Comment by irungentoo** [comment]
Send some files, don't accept them and restart the receiver makes some weird things happen. I also see a file being created at the receivers side before I accept the file which is most likely related.

**Comment by irungentoo** [comment]
https://gist.github.com/irungentoo/fd69036948c41137de70

Fixes some issues I found.

**Comment by GrayHatter** [comment]
will close #976

**Comment by irungentoo** [comment]
Merged.

**Pull request closed without merging**
