### PR TITLE
UI fixes to make things a bit more touch friendly.

### PR DESCRIPTION
**Pull request by GrayHatter**
Also added +x to tools/cross_compile becasue every ```git reset``` was getting old.

part of #787

### CODE REVIEW

**Comment by GrayHatter** [comment]
also closes #768

**Comment by tsudoko** [comment]
> pulled the friends list closer to the left
Why? It looks ugly. Also, the selected contact is supposed to be connected with the chat window, you broke them up.
I think the send message button is too large, but it may be just me.

**Comment by Doom032** [comment]
Placing the avatars to the left makes them collider with the scrollbar, which is not pretty:

inline

Also, the "send message" button is greyed out and unusable on groupchats.

The new send button and the screenshot button placements are great improvements though. Very nice. As well as removing unneeded scrollbars.

**Comment by tsudoko** [comment]
@Doom032 is that the whole friends list? It looks different on my system:

uTox compiled from grayhatter/uTox@d9f0134

**Comment by Doom032** [comment]
@tsudoko I checked. I'm on the same commit. Changing the width of µTox does not change the position of the friends list and avatars. I'm on Xubuntu.

**Comment by irungentoo** [comment]
The extra width does look weird.

**Comment by GrayHatter** [comment]
I plan to revert the friend list changes. I just haven't had the time to jump into the code for a while. I also have to work on the group chat buttons as well

- [ ] friends width
- [ ] group buttons

**Comment by GrayHatter** [comment]
can someone check out the new updates? let me know if it needs anything extra?

**Comment by tsudoko** [comment]
I think disabling group buttons instead of dropping them would be a better idea, but yeah, right now they serve no purpose in groupchats anyway.

---
Is that empty space between the chat window and the input box intentional?

---
Minor issue: the chat bubble doesn't look exactly like in the mockup:
 vs 
I think it's a bit important because that's how the chat bubble in the Tox logo looks like.

**Comment by irungentoo** [comment]
Looks fine, small issue though. The send button doesn't work in groups and for me it first appeared as greyed out in groups but I can't reproduce that behavior again.

Other than that it works.

**Comment by irungentoo** [comment]
Pressing enter to send text to group chats doesn't work either.

**Pull request merged**
