### PR TITLE
File system enhansements for win32 + *nix

### PR DESCRIPTION
**Pull request by GrayHatter**
windows, *nux:
    prompt before overwriting
windows:
    enforce write ablity via os

TODO:
- [ ] enforce 0600 on ~unix

### CODE REVIEW

**Comment by GrayHatter** [comment]
this will replace pr #732 

tagging @tsudoko for comment in other pr.

**Comment by towlie** [comment]
@GrayHatter shall your PR request Admin rights on Windows? Because it only opens a prompt that asks me to use the user directory instead for saving files when I try to save into "Programm Files" for example. (Windows 7)

**Comment by GrayHatter** [comment]
@towlie are you sure you meant this pull request?

**Comment by towlie** [comment]
@GrayHatter 
Yes, is there an other one for windows?
```
windows:
"enforce write ablity via os"
```
It sounds like it enables rights to write into special directories.

**Comment by GrayHatter** [comment]
@towlie  oh, no. The only changes I've made here for win32 is that windows won't give utox a file that's read only, or in a directory without write access. 

Unless I'm mistaken you're only asking, you're not seeing a bug correct?

Saving to %PROGRAMFILES% because you'd need to run utox as an admin (Don't do that!), otherwise Windows (correctly) won't allow you to write to the directory.

**Comment by towlie** [comment]
@GrayHatter Yes, it's not a bug it was a question.

**Pull request merged**
