### PR TITLE
Adding '.gitignore' file

### PR DESCRIPTION
**Pull request by muchweb**
This is more handy than running `make clean` before each commit.

### CODE REVIEW

**Comment by Doom032** [comment]
a .gitignore file was sneakily added in by pr #730

**Comment by GrayHatter** [comment]
By mistake I assure you. I usually rebase on upstream before submitting pull-requests...

**Comment by Doom032** [comment]
Hehe. I guess it doesn't really matter how it comes in, it's handy we have one now.

**Comment by muchweb** [comment]
@Doom032, sneaky indeed, haha :smile_cat: I am closing this

**Comment by GrayHatter** [comment]
Once the .gitignore becomes a bit more robust, we should .gitignore to itself to allow for custom .gitignore files.

**Pull request closed without merging**
