### PR TITLE
Italian translation: update

### PR DESCRIPTION
**Pull request by Ansa89**
And some makefile refinement.

### CODE REVIEW

**Comment by tsudoko** [comment]
You forgot about `CREATEGROUPCHAT`

**Comment by GrayHatter** [comment]
@Ansa89 would you be willing to add the `CREATEGROUPCHAT` localization too?

**Comment by col6y** [comment]
@GrayHatter it looks like @Ansa89 updated this PR to include `CREATEGROUPCHAT`, but might have not actually commented, so you might not have been notified.

**Comment by GrayHatter** [comment]
Thank you @col6y and @Ansa89 and @tsudoko

**Pull request merged**
